const seatMap = [
  {
    id: "01",
    area: "[grid-area:3/5]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "02",
    area: "[grid-area:3/6]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "03",
    area: "[grid-area:3/7]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "04",
    area: "[grid-area:3/8]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "05",
    area: "[grid-area:3/9]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "06",
    area: "[grid-area:3/10]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "07",
    area: "[grid-area:3/11]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "08",
    area: "[grid-area:3/12]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "09",
    area: "[grid-area:3/13]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "10",
    area: "[grid-area:3/14]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "11",
    area: "[grid-area:3/15]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "12",
    area: "[grid-area:3/16]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
];

export default seatMap;
