const seatMap = [
  {
    id: "",
    area: "[grid-area:4/7/4/19]",
    type: "text",
    body: "デバッグ用マップ",
    objectUrl: "",
  },
  {
    id: "01",
    area: "[grid-area:5/7]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "02",
    area: "[grid-area:5/8]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "03",
    area: "[grid-area:5/9]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "04",
    area: "[grid-area:5/10]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "05",
    area: "[grid-area:5/11]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "06",
    area: "[grid-area:5/12]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "07",
    area: "[grid-area:5/13]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "08",
    area: "[grid-area:5/14]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "09",
    area: "[grid-area:5/15]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "10",
    area: "[grid-area:5/16]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "11",
    area: "[grid-area:5/17]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "12",
    area: "[grid-area:5/18]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  {
    id: "o01",
    area: "[grid-area:6/7/8/9]",
    type: "object",
    body: "",
    objectUrl: "/seatMap/paying.svg",
  },
  {
    id: "o02",
    area: "[grid-area:6/9]",
    type: "object",
    body: "",
    objectUrl: "/seatMap/toilet.svg",
  },
  {
    id: "o03",
    area: "[grid-area:6/10/8/12]",
    type: "object",
    body: "",
    objectUrl: "/seatMap/shower.svg",
  },
  {
    id: "o04",
    area: "[grid-area:7/9]",
    type: "object",
    body: "",
    objectUrl: "/seatMap/scanner.svg",
  },
  {
    id: "o05",
    area: "[grid-area:6/12]",
    type: "object",
    body: "",
    objectUrl: "/seatMap/faucet.svg",
  },
  {
    id: "o06",
    area: "[grid-area:7/12]",
    type: "object",
    body: "",
    objectUrl: "/seatMap/qr-code.svg",
  },
  {
    id: "o07",
    area: "[grid-area:6/13/8/16]",
    type: "object",
    body: "",
    objectUrl: "/seatMap/money.svg",
  },
  {
    id: "o08",
    area: "[grid-area:6/17/8/20]",
    type: "object",
    body: "",
    objectUrl: "/seatMap/line.svg",
  },
  {
    id: "o09",
    area: "[grid-area:6/16/8/18]",
    type: "object",
    body: "",
    objectUrl: "/seatMap/substract.svg",
  },
];

export default seatMap;
