const seatMap = [
  {
    id: "01",
    area: "[grid-area:3/5]",
    type: "seat",
    body: "",
    objectUrl: "",
  },
  // {
  //   id: "02",
  //   area: "[grid-area:5/8]",
  //   type: "seat",
  //   body: "",
  //   objectUrl: "",
  // },
  // {
  //   id: "02",
  //   area: "[grid-area:3/6]",
  //   type: "seat",
  //   body: "",
  //   objectUrl: "",
  // },
  // {
  //   id: "03",
  //   area: "[grid-area:3/7]",
  //   type: "seat",
  //   body: "",
  //   objectUrl: "",
  // },
  // {
  //   id: "04",
  //   area: "[grid-area:3/8]",
  //   type: "seat",
  //   body: "",
  //   objectUrl: "",
  // },
  // {
  //   id: "05",
  //   area: "[grid-area:3/9]",
  //   type: "seat",
  //   body: "",
  //   objectUrl: "",
  // },
  // {
  //   id: "06",
  //   area: "[grid-area:3/10]",
  //   type: "seat",
  //   body: "",
  //   objectUrl: "",
  // },
  // {
  //   id: "07",
  //   area: "[grid-area:3/11]",
  //   type: "seat",
  //   body: "",
  //   objectUrl: "",
  // },
  // {
  //   id: "08",
  //   area: "[grid-area:3/12]",
  //   type: "seat",
  //   body: "",
  //   objectUrl: "",
  // },
  // {
  //   id: "09",
  //   area: "[grid-area:3/13]",
  //   type: "seat",
  //   body: "",
  //   objectUrl: "",
  // },
  // {
  //   id: "10",
  //   area: "[grid-area:3/14]",
  //   type: "seat",
  //   body: "",
  //   objectUrl: "",
  // },
  // {
  //   id: "11",
  //   area: "[grid-area:3/15]",
  //   type: "seat",
  //   body: "",
  //   objectUrl: "",
  // },
  // {
  //   id: "12",
  //   area: "[grid-area:3/16]",
  //   type: "seat",
  //   body: "",
  //   objectUrl: "",
  // },
  // {
  //   id: "o01",
  //   area: "[grid-area:4/5/6/7]",
  //   type: "object",
  //   body: "",
  //   objectUrl: "/seatMap/paying.svg",
  // },
  // {
  //   id: "o02",
  //   area: "[grid-area:4/7]",
  //   type: "object",
  //   body: "",
  //   objectUrl: "/seatMap/toilet.svg",
  // },
  // {
  //   id: "o03",
  //   area: "[grid-area:4/8/6/10]",
  //   type: "object",
  //   body: "",
  //   objectUrl: "/seatMap/shower.svg",
  // },
  // {
  //   id: "o04",
  //   area: "[grid-area:5/7]",
  //   type: "object",
  //   body: "",
  //   objectUrl: "/seatMap/scanner.svg",
  // },
  // {
  //   id: "o05",
  //   area: "[grid-area:4/10]",
  //   type: "object",
  //   body: "",
  //   objectUrl: "/seatMap/faucet.svg",
  // },
  // {
  //   id: "o06",
  //   area: "[grid-area:5/10]",
  //   type: "object",
  //   body: "",
  //   objectUrl: "/seatMap/qr-code.svg",
  // },
  // {
  //   id: "o07",
  //   area: "[grid-area:4/11/6/14]",
  //   type: "object",
  //   body: "",
  //   objectUrl: "/seatMap/money.svg",
  // },
  // {
  //   id: "o08",
  //   area: "[grid-area:4/12/6/16]",
  //   type: "object",
  //   body: "",
  //   objectUrl: "/seatMap/line.svg",
  // },
  // {
  //   id: "o09",
  //   area: "[grid-area:4/14/6/18]",
  //   type: "object",
  //   body: "",
  //   objectUrl: "/seatMap/substract.svg",
  // },
];

export default seatMap;
